# Nome da Actions:  
name: Snake Game Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display message
      run: echo "Olá, mundo! A Action está funcionando."
